version: "3.8"

services:
  gamingfingers-web:
    container_name: gamingfingers-web
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.echat-web.rule=Host(`gamingfingers.barron.app`)'
      - 'traefik.http.routers.echat-web.entrypoints=websecure'
      - 'traefik.http.routers.echat-web.tls.certresolver=letsencrypt'
      - 'traefik.http.services.echat-web.loadbalancer.server.port=3000'
