version: "3.4"


services:
  gamingfingers:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    restart: always
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - GENERATE_SOURCEMAP=false
    networks:
      - proxy
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.cashclock.rule=Host(`barron.app`)'
    - 'traefik.http.routers.cashclock.entrypoints=websecure'
    - 'traefik.http.routers.cashclock.tls.certresolver=letsencrypt'

networks:
  proxy:
    external: true
    name: proxy
