name: Build
on:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/bit-barron/maxipflege:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy-production:
    name: Deploy / Production
    runs-on: ubuntu-latest
    needs:
      - "docker-build"
    environment: production
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy / Production
        uses: gimlet-io/gimlet-artifact-shipper-action@v0.8.3
        with:
          DEPLOY: "true"
          ENV: "hetzner-k3s"
          APP: "gamingfingers"
        env:
          GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
          GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}
